# Generated by Django 4.2.1 on 2023-06-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audiobase', '0020_artist_artist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='show_ida',
            field=models.IntegerField(default='Will be shown here...', verbose_name='Ida'),
        ),
    ]
