# Generated by Django 4.2.1 on 2023-06-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Audiobase', '0022_alter_artist_show_ida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='show_ida',
        ),
    ]
