# Generated by Django 4.2.1 on 2023-06-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audiobase', '0023_remove_artist_show_ida'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='show_ida',
            field=models.IntegerField(default='-1', verbose_name='Ida'),
        ),
    ]
