# Generated by Django 4.2.1 on 2023-06-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audiobase', '0002_alter_album_bname_alter_album_gold_alter_album_plat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(verbose_name='Release year'),
        ),
    ]
