# Generated by Django 4.2.1 on 2023-06-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Audiobase', '0003_alter_album_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='bname',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='aname',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='n_gold',
            field=models.IntegerField(default=0, verbose_name='Gold records'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='n_plat',
            field=models.IntegerField(default=0, verbose_name='Platinum records'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='stagename',
            field=models.CharField(max_length=100, verbose_name='Stage name'),
        ),
        migrations.AlterField(
            model_name='song',
            name='sname',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
