# Generated by Django 4.2.1 on 2023-06-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Audiobase', '0006_alter_song_length_alter_song_spoty_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='pubdate',
            field=models.DateTimeField(),
        ),
    ]
