# Generated by Django 4.2.1 on 2023-06-04 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Audiobase', '0008_alter_song_pubdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='ida',
        ),
    ]
