# Generated by Django 4.2.1 on 2023-06-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Audiobase', '0009_remove_song_ida'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_name',
            field=models.CharField(default="album's name will appear here...", max_length=100, verbose_name='Album'),
        ),
        migrations.AddField(
            model_name='song',
            name='artist_name',
            field=models.CharField(default="artist's name will appear here...", max_length=100, verbose_name='Artist'),
        ),
    ]
