# Generated by Django 4.2.1 on 2023-06-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audiobase', '0011_alter_song_pubdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album_name',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist_name',
        ),
        migrations.AlterField(
            model_name='song',
            name='pubdate',
            field=models.DateField(verbose_name='Release year'),
        ),
    ]
