# Generated by Django 4.2.1 on 2023-06-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audiobase', '0012_remove_song_album_name_remove_song_artist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='pubdate',
            field=models.IntegerField(verbose_name='Release year'),
        ),
    ]
