# Generated by Django 4.2.1 on 2023-06-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audiobase', '0014_song_album_name_song_artist_name_alter_song_pubdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album_name',
            field=models.CharField(default='Album name will appear here...', max_length=100, verbose_name='Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist_name',
            field=models.CharField(default='Artist name will appear here...', max_length=100, verbose_name='Artist'),
        ),
    ]
