# Generated by Django 4.2.1 on 2023-06-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audiobase', '0015_alter_song_album_name_alter_song_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='pubdate',
            field=models.IntegerField(default='Same as the album...', verbose_name='Release year'),
        ),
    ]
