# Generated by Django 4.2.1 on 2023-06-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audiobase', '0018_alter_song_pubdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist_name',
            field=models.CharField(default='Artist name will appear here...', max_length=100, verbose_name='Artist'),
        ),
    ]
