# Generated by Django 4.2.1 on 2023-06-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Audiobase', '0021_artist_show_ida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='show_ida',
            field=models.IntegerField(blank=True, default=1, verbose_name='Ida'),
        ),
    ]
