# Generated by Django 4.2.1 on 2023-06-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Audiobase', '0024_alter_artist_show_ida'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_image',
            field=models.ImageField(blank=True, null=True, upload_to='album_img/'),
        ),
        migrations.AddField(
            model_name='album',
            name='show_idb',
            field=models.IntegerField(default=1, null=True, verbose_name='Ida'),
        ),
    ]
