# Generated by Django 4.2.1 on 2023-06-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Audiobase', '0025_album_album_image_album_show_idb'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0,
                                      verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='album',
            name='show_idb',
            field=models.IntegerField(default=-1, null=True, verbose_name='Idb'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='show_ida',
            field=models.IntegerField(default=-1, null=True, verbose_name='Ida'),
        ),
    ]
