# Generated by Django 4.2.1 on 2023-06-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Audiobase', '0026_artist_rating_alter_album_show_idb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='rating',
        ),
        migrations.AddField(
            model_name='album',
            name='best_album',
            field=models.IntegerField(default=0, verbose_name="Votes as artist's best album"),
        ),
    ]
